@extends('layouts.skeleton')
@section('title', 'Expediente Fundación Casa Ronald McDonald')
@section('description-page', 'Expediente y registro de entradas y salidas')
@section('titule-og', 'Expediente Fundación Casa Ronald McDonald')
@section('description-og', 'Expediente Fundación Casa Ronald McDonald y sistema de registro de entradas y salidas')
@section('description-tc', 'Expediente Fundación Casa Ronald McDonald y sistema de registro de entradas y salidas')
@section('description-td', 'Expediente Fundación Casa Ronald McDonald y sistema de registro de entradas y salidas')
@section('content')
	{{--@include('parts.navs')
	@include('contents.index')--}}
	@include('forms.ficha')
	@include('parts.sidebar')
	@include('forms.nino')
	@include('datatables.ninos')
@endsection